
/**
 *  注意配置文件中的控制器名称Key要保持一致 
 *  adminApi controllers 中的所有控制器名称key要保持一致
 *  具体功能路由配置重的 method 要与控制器中的方法名一致
 */

// 所有的路由都配置导这里
const PATCH  = 'patch'
const DELETE = 'delete'
const POST = 'post'
const GET = 'get'

// 调用api接口的路由
const adminApi = {
  ConsumerWwController:{
    name:'旺旺相关',
    routers:{
    consumerWwList:{
      path:'/api/v1/consumerWw/list',
      desc:'订单礼品',
      method:'consumerWwList',
      type:GET,
      selected:false,
    },
    consumerWwAdd:{
      path:'/api/v1/consumerWw/add',
      desc:'添加礼品',
      method:'consumerWwAdd',
      type:POST,
      selected:false
    },
    consumerWwEdit:{
      path:'/api/v1/consumerWw/edit/:id',
      desc:'修改礼品',
      method:'consumerWwEdit',
      type:POST,
      selected:false
    },
    consumerWwDelete:{
      path:'/api/v1/consumerWw/delete',
      desc:'删除旺旺',
      method:'consumerWwDelete',
      type:POST,
      selected:false,
    },
    consumerWwDetail:{
      path:'/api/v1/consumerWw/detail/:id',
      desc:'旺旺详情',
      method:'consumerWwDetail',
      type:GET,
      selected:false
    },
  }
},
  ShopkeeperController:{
    name:'客户管理相关',
    routers:{
      shopkeeperList:{
        path:'/api/v1/shopkeeper/list',
        desc:'客户列表',
        method:'shopkeeperList',
        type:GET,
        selected:false,
      },
      shopkeeperAdd:{
        path:'/api/v1/shopkeeper/add',
        desc:'添加客户',
        method:'shopkeeperAdd',
        type:POST,
        selected:false
      },
      shopkeeperEdit:{
        path:'/api/v1/shopkeeper/edit/:id',
        desc:'编辑客户',
        method:'shopkeeperEdit',
        type:POST,
        selected:false
      },
      shopkeeperDetail:{
        path:'/api/v1/shopkeeper/detail/:id',
        desc:'客户详情',
        method:'shopkeeperDetail',
        type:GET,
        selected:false
      },
      shopkeeperDelete:{
        path:'/api/v1/shopkeeper/delete',
        desc:'删除客户',
        method:'shopkeeperDelete',
        type:POST,
        selected:false,
      },
    }
  },
  ShopController:{
    name:'店铺管理相关',
    routers:{
      shopList:{
        path:'/api/v1/shop/list',
        desc:'商铺列表',
        method:'shopList',
        type:GET,
        selected:false,
      },
      shopAdd:{
        path:'/api/v1/shop/add',
        desc:'添加商铺',
        method:'shopAdd',
        type:POST,
        selected:false
      },
      shopEdit:{
        path:'/api/v1/shop/edit/:id',
        desc:'编辑商铺',
        method:'shopEdit',
        type:POST,
        selected:false
      },
      shopDetail:{
        path:'/api/v1/shop/detail/:id',
        desc:'店铺详情',
        method:'shopDetail',
        type:GET,
        selected:false
      },
      shopDelete:{
        path:'/api/v1/shop/delete',
        desc:'删除商铺',
        method:'shopDelete',
        type:POST,
        selected:false,
      },
    }
  },
  ProductController:{
    name:'商品管理相关',
    routers:{
      productList:{
        path:'/api/v1/product/list',
        desc:'商品列表',
        method:'productList',
        type:GET,
        selected:false,
      },
      productAdd:{
        path:'/api/v1/product/add',
        desc:'添加商品',
        method:'productAdd',
        type:POST,
        selected:false
      },
      productEdit:{
        path:'/api/v1/product/edit/:id',
        desc:'编辑商品',
        method:'productEdit',
        type:POST,
        selected:false
      },
      productDetail:{
        path:'/api/v1/product/detail/:id',
        desc:'商品详情',
        method:'productDetail',
        type:GET,
        selected:false
      },
      productDelete:{
        path:'/api/v1/product/delete',
        desc:'删除商品',
        method:'productDelete',
        type:POST,
        selected:false,
      },
      statusList:{
        path:'/api/v1/product/statusList',
        desc:'商品状态',
        method:'statusList',
        type:GET,
        selected:false,
      }
    }
  },
  ConsumerController:{
    name:'会员管理想滚',
    routers:{
      consumerList:{
        path:'/api/v1/consumer/list',
        desc:'会员列表',
        method:'consumerList',
        type:GET,
        selected:false,
      },
      consumerAdd:{
        path:'/api/v1/consumer/add',
        desc:'添加会员',
        method:'consumerAdd',
        type:POST,
        selected:false
      },
      consumerEdit:{
        path:'/api/v1/consumer/edit/:id',
        desc:'编辑会员',
        method:'consumerEdit',
        type:POST,
        selected:false
      },
      consumerDetail:{
        path:'/api/v1/consumer/detail/:id',
        desc:'会员详情',
        method:'consumerDetail',
        type:GET,
        selected:false
      },
      consumerDelete:{
        path:'/api/v1/consumer/delete',
        desc:'删除会员',
        method:'consumerDelete',
        type:POST,
        selected:false,
      },
    }
  },
}


// 导出
module.exports = {
  adminApi
}